<?php

namespace Mdespeuilles\WebformBundle;

use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\HttpKernel\Bundle\Bundle;

class MdespeuillesWebformBundle extends Bundle
{
    public function build(ContainerBuilder $container)
    {
        parent::build($container); // TODO: Change the autogenerated stub
        //$container->addCompilerPass(new RecaptchaComplierPass());
    }
}
