<?php

namespace Mdespeuilles\WebformBundle\Repository;

/**
 * WebformComponentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebformComponentRepository extends \Doctrine\ORM\EntityRepository
{
}
