<?php

namespace Mdespeuilles\WebformBundle\Repository;

/**
 * WebformRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebformRepository extends \Doctrine\ORM\EntityRepository
{
}
