<?php

namespace Mdespeuilles\WebformBundle\Repository;

/**
 * WebformSubmissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebformSubmissionRepository extends \Doctrine\ORM\EntityRepository
{
}
